### ISSUE TITLE
[NOT AN ISSUE] - DistroBox - DaVinci Helper doesn't launch with sudo in distrobox container

### ISSUE THREAD

**Issue by Zeglius** [H3rz3n/davinci-helper#16]
Distrobox container (fedora 41 image).
By running `davinci-helper` in terminal, shows needs to be run as root.
![image](https://github.com/user-attachments/assets/4f0113e4-b6fc-435b-a03c-ce1d13799f29)

Running with `sudo davinci-helper`, doesnt open the app:
```
📦[zeglius@distrobox-dKTcWwebJz ~]$ LC_all=C sudo davinci-helper 

(davinci-helper:113594): Gtk-WARNING **: 00:09:08.164: Unable to acquire session bus: Falló al ejecutar el proceso hijo «dbus-launch» (No existe el fichero o el directorio)
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Couldn't open libGLESv2.so.2: libGLESv2.so.2: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
Abortado
```

Running with `sudo -E davinci-helper`, it does opens the app, but still show the same error message as running without sudo:
![image](https://github.com/user-attachments/assets/53c9cba0-4ae7-486b-8a51-2d584f760b63)

**Comment by H3rz3n** [comment]
The issue is happening because DaVinci Helper uses Polkit to get root permission. I never tried Distrobox and I don't know if it supports the use of Polkit to get authentication. The idea behind DaVinci Helper is to run DaVinci Resolve natively on Fedora Linux, without using any type of container or intermediation.

**Comment by Malix-Labs** [comment]
_@H3rz3n could you close this issue as "not planned" instead of "completed" please? :)_

**Comment by Malix-Labs** [comment]
> The idea behind DaVinci Helper is to run DaVinci Resolve natively on Fedora Linux, without using any type of container or intermediation.

Would you also consider adding support for atomic systems (such as Fedora Atomic) ?

Those systems rely mostly on Flatpak / Distroboxes for packages

**Comment by H3rz3n** [comment]
> > The idea behind DaVinci Helper is to run DaVinci Resolve natively on Fedora Linux, without using any type of container or intermediation.
> 
> Would you also consider adding support for atomic systems (such as Fedora Atomic) ?
> 
> Those systems rely mostly on Flatpak / Distroboxes for GUIs

Maybe in the future, now the priority is to make a fully functional porting for Debian-based OS like Linux Mint, Ubuntu, ecc... .

I tried to make a Flatpack version of DaVinci Helper but I had some troubles with Polkit. Making a version for Distrobox would be probably easier because replacing polkit commands with sudo should be enough to make it compatible. If you have some spare time you can try yourself to replace those commands with sudo. (^_^)

**Comment by Malix-Labs** [comment]
> I tried to make a Flatpack version of DaVinci Helper but I had some troubles with Polkit

_Also see https://github.com/ublue-os/config/issues/339#issuecomment-2459947848 :)_

**Comment by gmankab** [comment]
> I tried to make a Flatpack version of DaVinci Helper but I had some troubles with Polkit.

i think i can help with troubles solving

@H3rz3n, can you share flatpak manifest you wrote?

**Comment by H3rz3n** [comment]
> > I tried to make a Flatpack version of DaVinci Helper but I had some troubles with Polkit.
> 
> i think i can help with troubles solving
> 
> @H3rz3n, can you share flatpak manifest you wrote?

I'm sorry but I don't have it anymore, i tried to make a flatpack version when I was trying to compile the first builds of the version 1. Thank you for your support ! (^_^)

**Comment by gmankab** [comment]
ok maybe i will try to write manifest from scratch
